version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule: 
      interval: "weekly"
    schedule.day: "monday"

  - packed-ecosystem: "docker"
    diretory: "/"
    schedule: 
      interval: "daily"